In [1]:
import pandas as pd

data_url = 'https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv'
cars = pd.read_csv(data_url)
cars.columns = ['car_names', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
cars.head()

car_names   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [2]:
cars.shape

(32, 12)

## Step 1: define the features

In [3]:
from sklearn.preprocessing import StandardScaler

# Extract only some subset of columns to reduce computation time 
X = cars[['mpg', 'disp', 'hp', 'wt']].values

# Standardize the features so that no feature dominates the
# distance computations due to unit scale
scaler = StandardScaler().fit(X)
X = scaler.transform(X)

## Step 2: define a distance metric

In [4]:
from sklearn.metrics.pairwise import euclidean_distances

## Step 3: recommend items

In [5]:
# Car the user is looking at
looking_at_car = [15, 300, 160, 3.2] #mpg, disp, hp, wt
looking_at_car = scaler.transform([looking_at_car])

# Distance from all other cars
distances = euclidean_distances(X, looking_at_car) # (n_rows1, n_cols), (n_rows2, n_cols) --> (n_rows1, n_rows2)
distances_reshaped = distances.reshape(-1)   # Before it was (n_cars, 1), now just one dimension

print(distances.shape)
distances

(32, 1)


array([[1.80329319],
       [1.73292868],
       [2.45498335],
       [1.35342452],
       [0.86167148],
       [1.17823806],
       [1.41066814],
       [2.48984573],
       [2.08868123],
       [1.42899598],
       [1.32798087],
       [0.99949458],
       [0.76183471],
       [0.70074137],
       [2.7504998 ],
       [2.88425915],
       [2.71229827],
       [3.86178746],
       [3.9230745 ],
       [4.20272927],
       [2.197629  ],
       [0.40155375],
       [0.28933564],
       [1.50940236],
       [1.29277697],
       [3.35368192],
       [2.80456301],
       [3.62140878],
       [1.6028164 ],
       [1.57829709],
       [2.62156131],
       [2.01953688]])

In [6]:
distances_reshaped

array([1.80329319, 1.73292868, 2.45498335, 1.35342452, 0.86167148,
       1.17823806, 1.41066814, 2.48984573, 2.08868123, 1.42899598,
       1.32798087, 0.99949458, 0.76183471, 0.70074137, 2.7504998 ,
       2.88425915, 2.71229827, 3.86178746, 3.9230745 , 4.20272927,
       2.197629  , 0.40155375, 0.28933564, 1.50940236, 1.29277697,
       3.35368192, 2.80456301, 3.62140878, 1.6028164 , 1.57829709,
       2.62156131, 2.01953688])

In [7]:
# Find the 3 indices with the minimum distance (highest similarity) to the car we're looking at
ordered_indices = distances_reshaped.argsort() #smallest values to largest
ordered_indices

array([22, 21, 13, 12,  4, 11,  5, 24, 10,  3,  6,  9, 23, 29, 28,  1,  0,
       31,  8, 20,  2,  7, 30, 16, 14, 26, 15, 25, 27, 17, 18, 19],
      dtype=int64)

In [8]:
closest_indices = ordered_indices[:3] # three closest

# Get the cars for these indices
closest_cars = cars.iloc[closest_indices]
closest_cars

#remember looking_at_car = [15, 300, 160, 3.2] #mpg, disp, hp, wt

car_names   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
22       AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3   
21  Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3   
13       Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3   

    carb  
22     2  
21     2  
13     3