### NLP Representations Exercise

In [1]:
# import pandas
import pandas as pd

# import CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
 
# import TfidfTransformer 
from sklearn.feature_extraction.text import TfidfTransformer

# import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
docs=["the house had a tiny little mouse",
      "the cat saw the mouse",
      "the mouse ran away from the house",
      "the cat finally ate the mouse",
      "the end of the mouse story"
     ]

# BagOfWords

* instantiate [CountVectorizer()](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html)

In [3]:
cv = CountVectorizer()

* use fit_transform method of CountVectorizer to 'docs' and store the result in 'word_count_vector'

In [4]:
word_count_vector = cv.fit_transform(docs)

* print the shape 

In [5]:
word_count_vector.shape

(5, 16)

* create dataframe from word_count_vector

In [6]:
column_names = cv.get_feature_names_out()
column_names

array(['ate', 'away', 'cat', 'end', 'finally', 'from', 'had', 'house',
       'little', 'mouse', 'of', 'ran', 'saw', 'story', 'the', 'tiny'],
      dtype=object)

In [7]:
data = word_count_vector.toarray()
data

array([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 0],
       [0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 2, 0],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 2, 0]], dtype=int64)

In [8]:
df = pd.DataFrame(data, columns=column_names)
df

ate  away  cat  end  finally  from  had  house  little  mouse  of  ran  \
0    0     0    0    0        0     0    1      1       1      1   0    0   
1    0     0    1    0        0     0    0      0       0      1   0    0   
2    0     1    0    0        0     1    0      1       0      1   0    1   
3    1     0    1    0        1     0    0      0       0      1   0    0   
4    0     0    0    1        0     0    0      0       0      1   1    0   

   saw  story  the  tiny  
0    0      0    1     1  
1    1      0    2     0  
2    0      0    2     0  
3    0      0    2     0  
4    0      1    2     0

# TfIdf with TfidfTransformer

* instantiate [TfidfTransformer()](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html) with the following parameters: 
    * smooth_idf = True
    * use_idf = True

In [9]:
Tfldf = TfidfTransformer(use_idf=True, smooth_idf=True)

* use fit_transform method of tfidf transformer on 'word_count_vector' created above and store the result in 'tf_idf_data'

In [10]:
tf_idf_data = Tfldf.fit_transform(word_count_vector)
tf_idf_data

<5x16 sparse matrix of type '<class 'numpy.float64'>'
	with 26 stored elements in Compressed Sparse Row format>

* create dataframe from 'tf_idf_data'

In [11]:
data = tf_idf_data.toarray()
data

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.49356209, 0.39820278, 0.49356209, 0.23518498,
        0.        , 0.        , 0.        , 0.        , 0.23518498,
        0.49356209],
       [0.        , 0.        , 0.48334378, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.28547062,
        0.        , 0.        , 0.59909216, 0.        , 0.57094124,
        0.        ],
       [0.        , 0.45709287, 0.        , 0.        , 0.        ,
        0.45709287, 0.        , 0.36877965, 0.        , 0.2178072 ,
        0.        , 0.45709287, 0.        , 0.        , 0.43561441,
        0.        ],
       [0.51392301, 0.        , 0.41462985, 0.        , 0.51392301,
        0.        , 0.        , 0.        , 0.        , 0.24488707,
        0.        , 0.        , 0.        , 0.        , 0.48977413,
        0.        ],
       [0.        , 0.        , 0.        , 0.49175319, 0.        ,
        0.        , 0.        , 

In [12]:
df = pd.DataFrame(data, columns=column_names)
df

ate      away       cat       end   finally      from       had  \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.493562   
1  0.000000  0.000000  0.483344  0.000000  0.000000  0.000000  0.000000   
2  0.000000  0.457093  0.000000  0.000000  0.000000  0.457093  0.000000   
3  0.513923  0.000000  0.414630  0.000000  0.513923  0.000000  0.000000   
4  0.000000  0.000000  0.000000  0.491753  0.000000  0.000000  0.000000   

      house    little     mouse        of       ran       saw     story  \
0  0.398203  0.493562  0.235185  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.285471  0.000000  0.000000  0.599092  0.000000   
2  0.368780  0.000000  0.217807  0.000000  0.457093  0.000000  0.000000   
3  0.000000  0.000000  0.244887  0.000000  0.000000  0.000000  0.000000   
4  0.000000  0.000000  0.234323  0.491753  0.000000  0.000000  0.491753   

        the      tiny  
0  0.235185  0.493562  
1  0.570941  0.000000  
2  0.435614  0.000000  
3  0.489774  0.000000  
4  0.468646  0.000000

* print the IDF for words in 'docs'

In [13]:
Tfldf.idf_

array([2.09861229, 2.09861229, 1.69314718, 2.09861229, 2.09861229,
       2.09861229, 2.09861229, 1.69314718, 2.09861229, 1.        ,
       2.09861229, 2.09861229, 2.09861229, 2.09861229, 1.        ,
       2.09861229])

# TfIdf with TfidfVectorizer

Equivalent to CountVectorizer followed by TfidfTransformer.

* instantiate [TfidfVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html) with the following parameters:
    - use_idf = True

In [14]:
Tfldf = TfidfVectorizer(use_idf=True)

* fit and transforn 'docs' with TfidfVectorizer and store the result in 'tfidf_vectorizer_data'

In [15]:
tf_vectorizer_data = Tfldf.fit_transform(docs)
tf_vectorizer_data

<5x16 sparse matrix of type '<class 'numpy.float64'>'
	with 26 stored elements in Compressed Sparse Row format>

* create dataframe from tfidf_vectorizer_data

In [16]:
data = tf_vectorizer_data.toarray()

In [17]:
df_tf_idf = pd.DataFrame(data, columns=column_names)

* print 'df_tf_idf'

In [18]:
df_tf_idf

ate      away       cat       end   finally      from       had  \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.493562   
1  0.000000  0.000000  0.483344  0.000000  0.000000  0.000000  0.000000   
2  0.000000  0.457093  0.000000  0.000000  0.000000  0.457093  0.000000   
3  0.513923  0.000000  0.414630  0.000000  0.513923  0.000000  0.000000   
4  0.000000  0.000000  0.000000  0.491753  0.000000  0.000000  0.000000   

      house    little     mouse        of       ran       saw     story  \
0  0.398203  0.493562  0.235185  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.285471  0.000000  0.000000  0.599092  0.000000   
2  0.368780  0.000000  0.217807  0.000000  0.457093  0.000000  0.000000   
3  0.000000  0.000000  0.244887  0.000000  0.000000  0.000000  0.000000   
4  0.000000  0.000000  0.234323  0.491753  0.000000  0.000000  0.491753   

        the      tiny  
0  0.235185  0.493562  
1  0.570941  0.000000  
2  0.435614  0.000000  
3  0.489774  0.000000  
4  0.468646  0.000000

* print IDF for words in 'docs'

In [19]:
Tfldf.idf_

array([2.09861229, 2.09861229, 1.69314718, 2.09861229, 2.09861229,
       2.09861229, 2.09861229, 1.69314718, 2.09861229, 1.        ,
       2.09861229, 2.09861229, 2.09861229, 2.09861229, 1.        ,
       2.09861229])